/* 18-Mar-2015 18:44:23 */
#ifndef STATIC_SCHEDULES_H_
#define STATIC_SCHEDULES_H_

#define NUMBER_OF_SLOTFRAMES 5
#define STATIC_SLOTFRAMES { \
  {1, 7, 33}, \
  {2, 7, 33}, \
  {3, 7, 33}, \
  {4, 7, 33}, \
  {5, 7, 33}, \
}

#define NUMBER_OF_LINKS 28
#define STATIC_LINKS { \
  {2, 1, 7, 1, 0, LINK_OPTION_TX | LINK_OPTION_TIME_KEEPING, LINK_TYPE_NORMAL}, \
  {1, 2, 7, 1, 0, LINK_OPTION_RX, LINK_TYPE_NORMAL}, \
  {2, 1, 7, 2, 0, LINK_OPTION_TX | LINK_OPTION_TIME_KEEPING, LINK_TYPE_NORMAL}, \
  {1, 2, 7, 2, 0, LINK_OPTION_RX, LINK_TYPE_NORMAL}, \
  {3, 1, 7, 3, 0, LINK_OPTION_TX | LINK_OPTION_TIME_KEEPING, LINK_TYPE_NORMAL}, \
  {1, 3, 7, 3, 0, LINK_OPTION_RX, LINK_TYPE_NORMAL}, \
  {3, 1, 7, 4, 0, LINK_OPTION_TX | LINK_OPTION_TIME_KEEPING, LINK_TYPE_NORMAL}, \
  {1, 3, 7, 4, 0, LINK_OPTION_RX, LINK_TYPE_NORMAL}, \
  {4, 2, 7, 5, 0, LINK_OPTION_TX | LINK_OPTION_TIME_KEEPING, LINK_TYPE_NORMAL}, \
  {2, 4, 7, 5, 0, LINK_OPTION_RX, LINK_TYPE_NORMAL}, \
  {4, 2, 7, 6, 0, LINK_OPTION_TX | LINK_OPTION_TIME_KEEPING, LINK_TYPE_NORMAL}, \
  {2, 4, 7, 6, 0, LINK_OPTION_RX, LINK_TYPE_NORMAL}, \
  {4, 2, 7, 7, 0, LINK_OPTION_TX | LINK_OPTION_TIME_KEEPING, LINK_TYPE_NORMAL}, \
  {2, 4, 7, 7, 0, LINK_OPTION_RX, LINK_TYPE_NORMAL}, \
  {2, 1, 7, 8, 0, LINK_OPTION_TX | LINK_OPTION_TIME_KEEPING, LINK_TYPE_NORMAL}, \
  {1, 2, 7, 8, 0, LINK_OPTION_RX, LINK_TYPE_NORMAL}, \
  {2, 1, 7, 9, 0, LINK_OPTION_TX | LINK_OPTION_TIME_KEEPING, LINK_TYPE_NORMAL}, \
  {1, 2, 7, 9, 0, LINK_OPTION_RX, LINK_TYPE_NORMAL}, \
  {5, 3, 7, 10, 0, LINK_OPTION_TX | LINK_OPTION_TIME_KEEPING, LINK_TYPE_NORMAL}, \
  {3, 5, 7, 10, 0, LINK_OPTION_RX, LINK_TYPE_NORMAL}, \
  {5, 3, 7, 11, 0, LINK_OPTION_TX | LINK_OPTION_TIME_KEEPING, LINK_TYPE_NORMAL}, \
  {3, 5, 7, 11, 0, LINK_OPTION_RX, LINK_TYPE_NORMAL}, \
  {5, 3, 7, 12, 0, LINK_OPTION_TX | LINK_OPTION_TIME_KEEPING, LINK_TYPE_NORMAL}, \
  {3, 5, 7, 12, 0, LINK_OPTION_RX, LINK_TYPE_NORMAL}, \
  {3, 1, 7, 13, 0, LINK_OPTION_TX | LINK_OPTION_TIME_KEEPING, LINK_TYPE_NORMAL}, \
  {1, 3, 7, 13, 0, LINK_OPTION_RX, LINK_TYPE_NORMAL}, \
  {3, 1, 7, 14, 0, LINK_OPTION_TX | LINK_OPTION_TIME_KEEPING, LINK_TYPE_NORMAL}, \
  {1, 3, 7, 14, 0, LINK_OPTION_RX, LINK_TYPE_NORMAL}, \
}

#endif /* STATIC_SCHEDULES_H_ */
