NET =						\
hc.c						\
nbr-table.c			\
netstack.c					\
packetbuf.c					\
packetqueue.c					\
psock.c						\
queuebuf.c					\
sicslowpan.c					\
simple-udp.c					\
tcpip.c						\
uip-debug.c					\
uip-ds6-route.c					\
uip-ds6-nbr.c				\
uip-ds6.c					\
uip-fw-drv.c					\
uip-fw.c					\
uip-icmp6.c					\
uip-nd6.c					\
uip-neighbor.c					\
uip-packetqueue.c				\
uip-udp-packet.c				\
uip.c						\
uip6.c						\
uiplib.c
